config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'publication_cards#index'

  resources :publication_cards do
    resources :messages
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :publication_card
end

app/models/publication_card.rb
# frozen_string_literal: true

class PublicationCard < ApplicationRecord
  has_many :messages
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :set_message, only: %i[show edit update destroy]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show; end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit; end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_url(@message), notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.require(:message).permit(:log)
  end
end

app/controllers/publication_cards_controller.rb
# frozen_string_literal: true

class PublicationCardsController < ApplicationController
  before_action :set_publication_card, only: %i[show edit update destroy]

  # GET /publication_cards or /publication_cards.json
  def index
    @publication_cards = PublicationCard.all
  end

  # GET /publication_cards/1 or /publication_cards/1.json
  def show; end

  # GET /publication_cards/new
  def new
    @publication_card = PublicationCard.new
  end

  # GET /publication_cards/1/edit
  def edit; end

  # POST /publication_cards or /publication_cards.json
  def create
    @publication_card = PublicationCard.new(publication_card_params)

    respond_to do |format|
      if @publication_card.save
        format.html do
          redirect_to publication_card_url(@publication_card), notice: 'Publication card was successfully created.'
        end
        format.json { render :show, status: :created, location: @publication_card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publication_cards/1 or /publication_cards/1.json
  def update
    respond_to do |format|
      if @publication_card.update(publication_card_params)
        format.html do
          redirect_to publication_card_url(@publication_card), notice: 'Publication card was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @publication_card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publication_cards/1 or /publication_cards/1.json
  def destroy
    @publication_card.destroy

    respond_to do |format|
      format.html { redirect_to publication_cards_url, notice: 'Publication card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_publication_card
    @publication_card = PublicationCard.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def publication_card_params
    params.require(:publication_card).permit(:url, :interval, :count, :title, :text, :status)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/publication_cards_helper.rb
# frozen_string_literal: true

module PublicationCardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Publication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Log:</strong>
    <%= message.log %>
  </p>

</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>

app/views/publication_cards/_form.html.erb
<%= form_with(model: publication_card) do |form| %>
  <% if publication_card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication_card.errors.count, "error") %> prohibited this publication_card from being saved:</h2>

      <ul>
        <% publication_card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :interval, style: "display: block" %>
    <%= form.number_field :interval %>
  </div>

  <div>
    <%= form.label :count, style: "display: block" %>
    <%= form.number_field :count %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publication_cards/_publication_card.html.erb
<div id="<%= dom_id publication_card %>">
  <p>
    <strong>Url:</strong>
    <%= publication_card.url %>
  </p>

  <p>
    <strong>Interval:</strong>
    <%= publication_card.interval %>
  </p>

  <p>
    <strong>Count:</strong>
    <%= publication_card.count %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= publication_card.title %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= publication_card.text %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= publication_card.status %>
  </p>

</div>

app/views/publication_cards/edit.html.erb
<h1>Editing publication card</h1>

<%= render "form", publication_card: @publication_card %>

<br>

<div>
  <%= link_to "Show this publication card", @publication_card %> |
  <%= link_to "Back to publication cards", publication_cards_path %>
</div>

app/views/publication_cards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Publication cards</h1>

<div id="publication_cards">
  <% @publication_cards.each do |publication_card| %>
    <%= render publication_card %>
    <p>
      <%= link_to "Show this publication card", publication_card %>
    </p>
  <% end %>
</div>

<%= link_to "New publication card", new_publication_card_path %>

app/views/publication_cards/new.html.erb
<h1>New publication card</h1>

<%= render "form", publication_card: @publication_card %>

<br>

<div>
  <%= link_to "Back to publication cards", publication_cards_path %>
</div>

app/views/publication_cards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @publication_card %>

<div>
  <%= link_to "Edit this publication card", edit_publication_card_path(@publication_card) %> |
  <%= link_to "Back to publication cards", publication_cards_path %>

  <%= button_to "Destroy this publication card", @publication_card, method: :delete %>
</div>